SELECT
    CPF_CNPJ = CAST(AA.TITULAR AS VARCHAR(15)),
    NOME_RAZAO = CAST(
        CASE
            WHEN (CHARINDEX('(', BB.NOME_RAZAO, 1) > 0) THEN LTRIM(
                RTRIM(
                    SUBSTRING(
                        BB.NOME_RAZAO,
                        1,
                        CHARINDEX('(', BB.NOME_RAZAO, 1) -1
                    )
                )
            )
            ELSE BB.NOME_RAZAO
        END AS VARCHAR(50)
    ),
    EMPRESA = (
        SELECT
            TOP 1 FF.FANTASIA
        FROM
            CLIfilial FF (NOLOCK)
        WHERE
            FF.CLIMATRIZ = AA.CLI0
            AND FF.CLIUNIDADE = AA.CLI1
    ),
    ENDERECO = CAST(NULL AS VARCHAR(100)),
    BAIRRO = CAST(NULL AS VARCHAR(50)),
    CIDADE = CAST(NULL AS VARCHAR(50)),
    CEP = CAST(NULL AS VARCHAR(10)),
    UF = CAST(NULL AS VARCHAR(5)),
    DDD_RES = CAST(NULL AS VARCHAR(5)),
    TELEFONE_RES = CAST(NULL AS VARCHAR(15)),
    DDD_COM = CAST(NULL AS VARCHAR(5)),
    TELEFONE_COM = CAST(NULL AS VARCHAR(15)),
    DDD_1 = CAST(NULL AS VARCHAR(5)),
    TELEFONE_1 = CAST(NULL AS VARCHAR(15)),
    DDD_2 = CAST(NULL AS VARCHAR(5)),
    TELEFONE_2 = CAST(NULL AS VARCHAR(15)),
    NUM_CTR = AA.NUMERO,
    BAIXADO = CASE
        WHEN (AA.BAIXADO = '0') THEN 'NAO'
        ELSE 'SIM'
    END,
    VENCIMENTO = AA.VENCIMENTO,
    VL_PARCELA = AA.SALDO,
    SALDO = AA.SALDO,
    EMAIL = (
        SELECT
            TOP 1 TE.EMAIL
        FROM
            tabEMAIL TE (NOLOCK)
        WHERE
            TE.CPF_CNPJ = BB.CPF_CNPJ
            AND TE.EMAIL IS NOT NULL
    ),
    ENDERECO_COM = CAST(NULL AS VARCHAR(100)),
    BAIRRO_COM = CAST(NULL AS VARCHAR(50)),
    CIDADE_COM = CAST(NULL AS VARCHAR(50)),
    CEP_COM = CAST(NULL AS VARCHAR(10)),
    UF_COM = CAST(NULL AS VARCHAR(5)),
    UC = CASE
        WHEN LTRIM(RTRIM(AA.CAMPO_ADC1)) <> '' THEN AA.CAMPO_ADC1
        WHEN CHARINDEX('CAMPO02:', AA.LAYOUT) > 0 THEN CAST(
            SUBSTRING(
                AA.LAYOUT,
                CHARINDEX('CAMPO01:', AA.LAYOUT) + 8,
                CHARINDEX('CAMPO02:', AA.LAYOUT) - CHARINDEX('CAMPO01:', AA.LAYOUT) - 8
            ) AS VARCHAR(25)
        )
        WHEN CHARINDEX('CAMPO01:', AA.LAYOUT) > 0 THEN CAST(SUBSTRING(AA.LAYOUT, 9, 50) AS VARCHAR(25))
        ELSE ''
    END,
    ORIGEM = AA.CAMPO_ADC3,
    OPERACAO = BO.OPERACAO,
    EMISSAO = BO.EMISSAO,
    VENC_BOLETO = BO.VENCIMENTO,
    PARCELA = BO.PARCELA,
    PLANO = CAST(BO.PARCELA + 1 AS VARCHAR(6)) + '/' + CAST(BO.PLANO AS VARCHAR(6)),
    VALOR = BO.VALOR,
    NOSSONUMERO = BO.NOSSONUMERO,
    PAGAMENTO = BO.PAGAMENTO,
    VALOR_PAGO = (
        SELECT
            TOP 1 RP.VALOR_PAGO
        FROM
            RECPG RP(NOLOCK)
        WHERE
            RP.CONTROLE_BOL = BO.CONTROLE
            AND RP.ONOFF = 1
    ),
    COMISSAO = (
        SELECT
            SUM(ISNULL(COMISSAO, 0))
        FROM
            REC00 DP (NOLOCK)
        WHERE
            ONOFF = 1
            AND DP.CPF_CNPJ = BO.CPF_CNPJ
            AND DP.OPERACAO = BO.OPERACAO
            AND DP.PARCELA = BO.PARCELA
    ),
    PCT_COMISSAO = CAST(NULL AS NUMERIC),
    COBRADOR_ACORDO = (
        SELECT
            USUARIO
        FROM
            USUARIOS UU (NOLOCK)
        WHERE
            UU.CONTROLE = BO.CODUSU
    ),
    STATUS = CASE
        WHEN BO.STATUS = 1 THEN 'ATIVO'
        WHEN BO.STATUS = 2 THEN 'PAGO'
        WHEN BO.STATUS = 3 THEN 'QUEBRA'
    END INTO ##TEMP_PESQ    FROM DEV03 AA (NOLOCK) INNER JOIN REC00 BO (NOLOCK) ON AA.TITULAR = BO.CPF_CNPJ     DEV00 BB (NOLOCK)WHERE AA.TITULAR=BB.CPF_CNPJ AND ((AA.EMP0=0001 AND AA.EMP1=0001)) AND ((AA.CLI0=0020 AND AA.CLI1=0001) OR (AA.CLI0=0028 AND AA.CLI1=0001))